language: node_js
node_js:
- '0.12'

sudo: false
cache: node_modules

git:
  submodules: false

before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init src/bootstrap
- gem install compass

script:
- npm start
